<?php
/**
 * Created by PhpStorm.
 * User: thanh
 * Date: 13/03/2019
 * Time: 17:24
 */
return [
    '1' => 'An Giang',
    '2' => 'Bà Rịa - Vũng Tàu',
    '3' => 'Bắc Giang',
    '4' => 'Bắc Kạn',
    '5' => 'Bạc Liêu',
    '6' => 'Bắc Ninh',
    '7' => 'Bến Tre',
    '8' => 'Bình Định',
    '9' => 'Bình Dương',
    '10' => 'Bình Phước',
    '11' => 'Bình Thuận',
    '12' => 'Cà Mau',
    '13' => 'Cao Bằng',
    '14' => 'Đắk Lắk',
    '15' => 'Đắk Nông',
    '16' => 'Điện Biên',
    '17' => 'Đồng Nai',
    '18' => 'Đồng Tháp',
    '19' => 'Gia Lai',
    '20' => 'Hà Giang',
    '21' => 'Hà Nam',
    '22' => 'Hà Tĩnh',
    '23' => 'Hải Dương',
    '24' => 'Hậu Giang',
    '25' => 'Hòa Bình',
    '26' => 'Hưng Yên',
    '27' => 'Khánh Hòa',
    '28' => 'Kiên Giang',
    '29' => 'Kon Tum',
    '30' => 'Lai Châu',
    '31' => 'Lâm Đồng',
    '32' => 'Lạng Sơn',
    '33' => 'Lào Cai',
    '34' => 'Long An',
    '35' => 'Nam Định',
    '36' => 'Nghệ An',
    '37' => 'Ninh Bình',
    '38' => 'Ninh Thuận',
    '39' => 'Phú Thọ',
    '40' => 'Quảng Bình',
    '41' => 'Quảng Nam',
    '42' => 'Quảng Ngãi',
    '43' => 'Quảng Ninh',
    '44' => 'Quảng Trị',
    '45' => 'Sóc Trăng',
    '46' => 'Sơn La',
    '47' => 'Tây Ninh',
    '48' => 'Thái Bình',
    '49' => 'Thái Nguyên',
    '50' => 'Thanh Hóa',
    '51' => 'Thừa Thiên Huế',
    '52' => 'Tiền Giang',
    '53' => 'Trà Vinh',
    '54' => 'Tuyên Quang',
    '55' => 'Vĩnh Long',
    '56' => 'Vĩnh Phúc',
    '57' => 'Yên Bái',
    '58' => 'Phú Yên',
    '59' => 'Cần Thơ',
    '60' => 'Đà Nẵng',
    '61' => 'Hải Phòng',
    '62' => 'Hà Nội',
    '63' => 'TP HCM',
];